name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: .
        tags: midlang:latest
        outputs: type=docker,dest=/tmp/midlang.tar
    - uses: actions/upload-artifact@v3
      with:
        name: midlang
        path: /tmp/midlang.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    env:
      RUSTFLAGS: -D warnings
    strategy:
      fail-fast: false
      matrix:
        test-case: ["hello-world", "hello-world2", "hello-world-cond"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/download-artifact@v3
      with:
        name: midlang
        path: /tmp

    - name: Compile
      run: make compile

    - name: Run tests
      run: make tests

    - name: Check fmt and clippy
      run: make check

    - name: Compile and run ${{ matrix.test-case }}
      run: make ${{ matrix.test-case }}