name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Create dev image, compile and test
      run: make

    - name: Check fmt and clippy
      run: make check