name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Create dev image
      run: make dev-env

    - name: Compile
      run: make compile

    - name: Check fmt and clippy
      run: make check

    - name: Unit tests
      run: make tests

    - name: Integration tests
      run: make integration-tests